version: "3"

services:
  app:
    # image: mongodb-app
    # container_name: mongodb-app
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npx ts-node -T src/index.ts
  mongodb:
    image: mongo:4.2.8-bionic
    volumes:
      - ./raw_db:/data/db
    ports:
      - 27017:27017
    # environment: 
      # - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
    restart: unless-stopped

networks:
  default:
    name: network_name